name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o luidium-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o luidium-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o luidium-darwin-amd64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Package Linux and macOS Release
        run: |
          mkdir luidium-linux-macos
          cp luidium-linux-amd64 luidium-linux-macos/luidium-linux-amd64
          cp luidium-darwin-amd64 luidium-linux-macos/luidium-darwin-amd64
          cp scripts/setup.sh luidium-linux-macos/setup.sh
          tar -czf luidium-linux-macos.tar.gz luidium-linux-macos/

      - name: Package Windows Release
        run: |
          mkdir luidium-windows
          cp luidium-windows-amd64.exe luidium-windows/luidium-windows-amd64.exe
          cp scripts/setup.bat luidium-windows/setup.bat
          zip -r luidium-windows.zip luidium-windows/

      - name: Upload Linux and macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./luidium-linux-macos.tar.gz
          asset_name: luidium-linux-macos.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./luidium-windows.zip
          asset_name: luidium-windows.zip
          asset_content_type: application/zip
